name: reconEnv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - colorama=0.4.4
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - h5py=3.2.1
  - hdf5=1.10.6
  - icu=58.2
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.42.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.4.3
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.3.1
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.0.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.11
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.9.0
  - pytz=2021.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tornado=6.1
  - tqdm=4.62.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
